[package]
name = "sensor-swarm"
version = "0.1.0"
edition = "2021"

[features]
default = ["blackpill-f401", "embedded"]
blackpill-f401 = []
std = []
embedded = [
    "embassy-executor",
    "embassy-time", 
    "embassy-stm32",
    "embassy-usb",
    "defmt",
    "defmt-rtt",
    "panic-probe",
    "cortex-m",
    "cortex-m-rt"
]

[dependencies]
# Embedded dependencies - only for non-test builds
embassy-executor = { version = "0.5.0", features = ["arch-cortex-m", "executor-thread", "defmt", "integrated-timers"], optional = true }
embassy-time = { version = "0.3.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"], optional = true }
embassy-stm32 = { version = "0.1.0", features = ["defmt", "stm32f401ce", "unstable-pac", "memory-x", "time-driver-any", "exti", "time"], optional = true }
embassy-usb = { version = "0.1.0", features = ["defmt"], optional = true }

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"], optional = true }
cortex-m-rt = { version = "0.7.0", optional = true }

# Non-embedded dependencies that work in both environments
bitfield-struct = "0.8"
heapless = "0.8"
