[target.thumbv7em-none-eabihf]
runner = ["gdb-multiarch", "-q"]
rustflags = [
  "-C", "link-arg=-Tlink.x"
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["probe-rs", "run", "--chip", "STM32F401CEUx"]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
