[target.thumbv7em-none-eabihf]
#runner = ["gdb-multiarch", "-q"]
runner = "./qemu-runner.sh"
rustflags = [
  "-C", "link-arg=-Tlink.x"
]


[target.'cfg(all(target_arch = "arm", target_os = "none", test))']
runner = "./qemu-runner.sh"


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["probe-rs", "run", "--chip", "STM32F401CEUx"]


[build]
target = "thumbv7em-none-eabihf"


[env]
DEFMT_LOG = "trace"
